<div class="online-form">
    <select class="form-control input-sm" id="destination" name="destination">
        <option disabled="disabled" value="" selected="selected">--selectati--</option>
        <option value="AFRICA">AFRICA</option>
        <option value="AMERICA, NORTH">AMERICA, NORTH</option>
        <option value="AMERICA, SOUTH">AMERICA, SOUTH</option>
        <option value="ASIA">ASIA</option>
        <option value="Albania EU">Albania EU</option>
        <option value="Algeria">Algeria</option>
        <option value="All World">All World</option>
        <option value="American Samoa">American Samoa</option>
        <option value="American Virgin Islands">American Virgin Islands</option>
        <option value="Andorra EU">Andorra EU</option>
        <option value="Angola">Angola</option>
        <option value="Anguilla">Anguilla</option>
        <option value="Antigua and Barbuda">Antigua and Barbuda</option>
        <option value="Antilles, Netherlands">Antilles, Netherlands</option>
        <option value="Argentina">Argentina</option>
        <option value="Armenia">Armenia</option>
        <option value="Aruba">Aruba</option>
        <option value="Australia">Australia</option>
        <option value="Austria EU">Austria EU</option>
        <option value="Azerbaijan">Azerbaijan</option>
        <option value="Bahamas">Bahamas</option>
        <option value="Bahrain">Bahrain</option>
        <option value="Bangladesh">Bangladesh</option>
        <option value="Barbados">Barbados</option>
        <option value="Belarus (Byelorussia) EU">Belarus (Byelorussia) EU</option>
        <option value="Belgium EU">Belgium EU</option>
        <option value="Belize">Belize</option>
        <option value="Benin">Benin</option>
        <option value="Bermuda">Bermuda</option>
        <option value="Bhutan">Bhutan</option>
        <option value="Bolivia">Bolivia</option>
        <option value="Bosnia-Herzegovina EU">Bosnia-Herzegovina EU</option>
        <option value="Botswana">Botswana</option>
        <option value="Brazil">Brazil</option>
        <option value="British Virgin Islands">British Virgin Islands</option>
        <option value="Brunei">Brunei</option>
        <option value="Bulgaria EU">Bulgaria EU</option>
        <option value="Burkina Faso">Burkina Faso</option>
        <option value="Burundi">Burundi</option>
        <option value="CSI">CSI</option>
        <option value="Cambodia">Cambodia</option>
        <option value="Cameroon">Cameroon</option>
        <option value="Canada">Canada</option>
        <option value="Canary Islands">Canary Islands</option>
        <option value="Cape Verde Islands">Cape Verde Islands</option>
        <option value="Cayman Islands">Cayman Islands</option>
        <option value="Central African Republic">Central African Republic</option>
        <option value="Chad">Chad</option>
        <option value="Channel Islands (Guernsey)">Channel Islands (Guernsey)</option>
        <option value="Channel Islands (Jersey)">Channel Islands (Jersey)</option>
        <option value="Chile">Chile</option>
        <option value="China, People's Republic of">China, People's Republic of</option>
        <option value="Colombia">Colombia</option>
        <option value="Congo (Brazzaville)">Congo (Brazzaville)</option>
        <option value="Congo, Democratic Republic of">Congo, Democratic Republic of</option>
        <option value="Cook Islands">Cook Islands</option>
        <option value="Costa Rica">Costa Rica</option>
        <option value="Cote d'Ivoire (Ivory Coast)">Cote d'Ivoire (Ivory Coast)</option>
        <option value="Croatia EU">Croatia EU</option>
        <option value="Cuba">Cuba</option>
        <option value="Cyprus EU">Cyprus EU</option>
        <option value="Czech Republic EU">Czech Republic EU</option>
        <option value="Denmark EU">Denmark EU</option>
        <option value="Djibouti">Djibouti</option>
        <option value="Dominica">Dominica</option>
        <option value="Dominican Republic">Dominican Republic</option>
        <option value="EUROPE">EUROPE</option>
        <option value="East Timor">East Timor</option>
        <option value="Ecuador">Ecuador</option>
        <option value="Egypt">Egypt</option>
        <option value="El Salvador">El Salvador</option>
        <option value="Equatorial Guinea">Equatorial Guinea</option>
        <option value="Eritrea">Eritrea</option>
        <option value="Estonia EU">Estonia EU</option>
        <option value="Ethiopia">Ethiopia</option>
        <option value="Faroe Islands">Faroe Islands</option>
        <option value="Fiji">Fiji</option>
        <option value="Finland EU">Finland EU</option>
        <option value="France EU">France EU</option>
        <option value="French Guiana">French Guiana</option>
        <option value="Gabon">Gabon</option>
        <option value="Gambia">Gambia</option>
        <option value="Gaza (West Bank)">Gaza (West Bank)</option>
        <option value="Georgia">Georgia</option>
        <option value="Germany EU">Germany EU</option>
        <option value="Ghana">Ghana</option>
        <option value="Gibraltar">Gibraltar</option>
        <option value="Greece EU">Greece EU</option>
        <option value="Greenland">Greenland</option>
        <option value="Grenada">Grenada</option>
        <option value="Guadeloupe">Guadeloupe</option>
        <option value="Guam">Guam</option>
        <option value="Guatemala">Guatemala</option>
        <option value="Guinea">Guinea</option>
        <option value="Guinea Bissau">Guinea Bissau</option>
        <option value="Guyana">Guyana</option>
        <option value="Haiti">Haiti</option>
        <option value="Honduras">Honduras</option>
        <option value="Hong Kong">Hong Kong</option>
        <option value="Hungary EU">Hungary EU</option>
        <option value="Iceland EU">Iceland EU</option>
        <option value="India">India</option>
        <option value="Indonesia">Indonesia</option>
        <option value="Iran">Iran</option>
        <option value="Iraq">Iraq</option>
        <option value="Ireland, Republic of EU">Ireland, Republic of EU</option>
        <option value="Israel EU">Israel EU</option>
        <option value="Italy EU">Italy EU</option>
        <option value="Jamaica">Jamaica</option>
        <option value="Japan">Japan</option>
        <option value="Jordan">Jordan</option>
        <option value="Kazakhstan">Kazakhstan</option>
        <option value="Kenya">Kenya</option>
        <option value="Kiribati">Kiribati</option>
        <option value="Korea, North">Korea, North</option>
        <option value="Korea, South">Korea, South</option>
        <option value="Kosovo">Kosovo</option>
        <option value="Kuwait">Kuwait</option>
        <option value="Kyrgyzstan">Kyrgyzstan</option>
        <option value="Laos">Laos</option>
        <option value="Latvia EU">Latvia EU</option>
        <option value="Lebanon">Lebanon</option>
        <option value="Lesotho">Lesotho</option>
        <option value="Liberia">Liberia</option>
        <option value="Libya">Libya</option>
        <option value="Liechtenstein">Liechtenstein</option>
        <option value="Lithuania EU">Lithuania EU</option>
        <option value="Luxembourg EU">Luxembourg EU</option>
        <option value="Macau">Macau</option>
        <option value="Macedonia (FYROM) EU">Macedonia (FYROM) EU</option>
        <option value="Madagascar">Madagascar</option>
        <option value="Malawi">Malawi</option>
        <option value="Malaysia">Malaysia</option>
        <option value="Maldives">Maldives</option>
        <option value="Mali">Mali</option>
        <option value="Malta EU">Malta EU</option>
        <option value="Marshall Islands">Marshall Islands</option>
        <option value="Martinique">Martinique</option>
        <option value="Mauritania">Mauritania</option>
        <option value="Mauritius">Mauritius</option>
        <option value="Mexico">Mexico</option>
        <option value="Micronesia (Federated States of)">Micronesia (Federated States of)</option>
        <option value="Monaco">Monaco</option>
        <option value="Mongolia">Mongolia</option>
        <option value="Montenegro">Montenegro</option>
        <option value="Montserrat">Montserrat</option>
        <option value="Morocco">Morocco</option>
        <option value="Mozambique">Mozambique</option>
        <option value="Namibia">Namibia</option>
        <option value="Nepal">Nepal</option>
        <option value="Netherlands, The EU (Holland)">Netherlands, The EU (Holland)</option>
        <option value="Nevis (St. Kitts)">Nevis (St. Kitts)</option>
        <option value="New Caledonia">New Caledonia</option>
        <option value="New Zealand">New Zealand</option>
        <option value="Nicaragua">Nicaragua</option>
        <option value="Niger">Niger</option>
        <option value="Nigeria">Nigeria</option>
        <option value="Northern Mariana Islands">Northern Mariana Islands</option>
        <option value="Norway EU">Norway EU</option>
        <option value="Oman">Oman</option>
        <option value="Pakistan">Pakistan</option>
        <option value="Palau">Palau</option>
        <option value="Panama">Panama</option>
        <option value="Papua New Guinea">Papua New Guinea</option>
        <option value="Paraguay">Paraguay</option>
        <option value="Peru">Peru</option>
        <option value="Philippines">Philippines</option>
        <option value="Poland EU">Poland EU</option>
        <option value="Portugal EU">Portugal EU</option>
        <option value="Puerto Rico">Puerto Rico</option>
        <option value="Qatar">Qatar</option>
        <option value="Reunion">Reunion</option>
        <option value="Romania EU">Romania EU</option>
        <option value="Russia EU">Russia EU</option>
        <option value="Rwanda">Rwanda</option>
        <option value="SCHENGEN">SCHENGEN</option>
        <option value="SCHENGEN/EUROPE">SCHENGEN/EUROPE</option>
        <option value="San Marino">San Marino</option>
        <option value="Saudi Arabia">Saudi Arabia</option>
        <option value="Senegal">Senegal</option>
        <option value="Serbia EU">Serbia EU</option>
        <option value="Seychelles">Seychelles</option>
        <option value="Sierra Leone">Sierra Leone</option>
        <option value="Singapore">Singapore</option>
        <option value="Slovak Republic EU">Slovak Republic EU</option>
        <option value="Slovenia EU">Slovenia EU</option>
        <option value="Solomon Islands">Solomon Islands</option>
        <option value="South Africa">South Africa</option>
        <option value="Spain EU">Spain EU</option>
        <option value="Sri Lanka">Sri Lanka</option>
        <option value="St. Lucia">St. Lucia</option>
        <option value="St. Vincent and the Grenadines">St. Vincent and the Grenadines</option>
        <option value="Suriname">Suriname</option>
        <option value="Swaziland">Swaziland</option>
        <option value="Sweden EU">Sweden EU</option>
        <option value="Switzerland EU">Switzerland EU</option>
        <option value="Syria">Syria</option>
        <option value="Tahiti">Tahiti</option>
        <option value="Taiwan">Taiwan</option>
        <option value="Tajikistan">Tajikistan</option>
        <option value="Tanzania">Tanzania</option>
        <option value="Thailand">Thailand</option>
        <option value="Thailand">Thailand</option>
        <option value="Toate ţările lumii">Toate ţările lumii</option>
        <option value="Togo">Togo</option>
        <option value="Tonga">Tonga</option>
        <option value="Trinidad and Tobago">Trinidad and Tobago</option>
        <option value="Tunisia">Tunisia</option>
        <option value="Turkey EU">Turkey EU</option>
        <option value="Turkmenistan">Turkmenistan</option>
        <option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
        <option value="Tuvalu">Tuvalu</option>
        <option value="Uganda">Uganda</option>
        <option value="Ukraine EU">Ukraine EU</option>
        <option value="United Arab Emirates">United Arab Emirates</option>
        <option value="United Kingdom EU">United Kingdom EU</option>
        <option value="United States">United States</option>
        <option value="Uruguay">Uruguay</option>
        <option value="Uzbekistan">Uzbekistan</option>
        <option value="Vanuatu">Vanuatu</option>
        <option value="Venezuela">Venezuela</option>
        <option value="Vietnam">Vietnam</option>
        <option value="Wallis and Futuna Islands">Wallis and Futuna Islands</option>
        <option value="Western Samoa">Western Samoa</option>
        <option value="Yemen, Republic of">Yemen, Republic of</option>
        <option value="Zambia">Zambia</option>
        <option value="Zimbabwe">Zimbabwe</option>
        <option value="Great Britain">Great Britain</option>
    </select>

    <input type="date" name="date" placeholder="Începutul valabilităţii poliţei de asigurare">
    <input type="date" name="end" placeholder="Sfirșitul valabilităţii poliţei de asigurare">

    <select class="form-control input-sm" id="type" name="type">
        <option value="Turism">Turism</option>
        <option value="Munca fizică">Munca fizică</option>
        <option value="Sport activ">Sport activ</option>
    </select>

    <input type="tel" name="phone" placeholder="Numărul de telefon">
    <input type="email" name="email" placeholder="E-mail">
    <div class="online-form__checkbox">
        <input type="checkbox" name="termen" id="checkbox-termen">
        <label for="checkbox-termen"><a href="#">Accept Termenii şi Condiţiile</a></label>
    </div>
    <div class="online-form__checkbox">
        <input type="checkbox" name="prelucrare" id="checkbox-prelucrare">
        <label for="checkbox-prelucrare"><a href="#">Accept Prelucrarea datelor cu caracter personal.</a></label>
    </div>
	<?php require_once __DIR__.'/online-form-delivery.php';?>
    <input class="btn btn-info" type="submit" value="Trimite">
</div>
<span><?php echo esc_html__( 'După plasarea comenzii, operatorul va prelua discuţia în JivoChat sau veţi fi apelat în scurt timp.', 'bs-galadent' ); ?></span>
